### ISSUE TITLE
Using in an ESM Module

### ISSUE THREAD

**Issue by icabetong** [arklanq/next-recompose-plugins#4]
Hello, I was wondering if how to use this library for ESM modules? Thank you.

**Comment by arklanq** [comment]
You should be able to use `"type": "module"` in package.json or at least `nest.config.mjs` file, but I have found out that there is a bug that prevents importing this package. I will address this issue in the next release, thanks.

**Comment by avarayr** [comment]
Any updates on this? I'd really like to use but I get an error on build
```
(node:78028) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:78028) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
 ⨯ Failed to load next.config.mjs, see more info here https://nextjs.org/docs/messages/next-config-error

> Build error occurred ./node_modules/.pnpm/next-recompose-plugins@2.0.2_next@14.1.4/node_modules/next-recompose-plugins/dist/esm/main.js:1
export { Config } from './Config.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:356:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:305:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by avarayr** [comment]
> I apologize for the delay, I've recently had very little time for my side projects. I will address this issue over the coming week.

No need for apology :) Take your time

**Comment by arklanq** [comment]
@icabetong @avarayr Can you check if this version works for you? [3.0.0-canary.1](https://www.npmjs.com/package/next-recompose-plugins/v/3.0.0-canary.1). I don't want to make this version public until I'm sure everything works. I checked this version quite thoroughly and it works fine for me, but extra confirmation from you will be great.

**Comment by icabetong** [comment]
I tested it with the repository that I'm going to use it with; it's seems it works fine.

**Comment by Finelai** [comment]
It would be helpful to include an ESM example in the documentation.
@icabetong , could you please provide a usage example?
